version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm audit fix
      - ls -la
  pre_build:
    commands:
      - echo "All dependencies installed successfully..."
  build:
    commands:
      - echo "Building the Lambda function..."
      - zip -r function.zip ./*
  post_build:
    commands:
      - echo "Updating the Lambda function code..."
      - aws lambda update-function-code --function-name nodejs-app --zip-file fileb://function.zip
artifacts:
  files:
    - function.zip
